# Generated by Django 2.2.3 on 2019-12-06 06:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pors_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='priapplicantexamscorescct',
            name='applicant_exam_score_scct',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sapplicant_exam_score_scct_fk', to='pors_app.PRIApplicantProfileInfo'),
        ),
    ]
