# Generated by Django 2.2.3 on 2019-12-06 08:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pors_app', '0007_auto_20191206_1607'),
    ]

    operations = [
        migrations.AlterField(
            model_name='priapplicantexamscorearpinfo',
            name='applicant_exam_score_arp',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='applicant_exam_score_arp_fk', to='pors_app.PRIApplicantProfileInfo'),
        ),
        migrations.AlterField(
            model_name='priapplicantexamscoreccainfo',
            name='applicant_exam_score_cca',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='applicant_exam_score_cca_fk', to='pors_app.PRIApplicantProfileInfo'),
        ),
        migrations.AlterField(
            model_name='priapplicantexamscorescctinfo',
            name='applicant_exam_score_scct',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='applicant_exam_score_scct_fk', to='pors_app.PRIApplicantProfileInfo'),
        ),
        migrations.AlterField(
            model_name='priapplicantexamscoret2seinfo',
            name='applicant_exam_score_t2se',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='applicant_exam_score_t2se_fk', to='pors_app.PRIApplicantProfileInfo'),
        ),
        migrations.AlterField(
            model_name='priapplicantexamscoret3einfo',
            name='applicant_exam_score_t3e',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='applicant_exam_score_t3e_fk', to='pors_app.PRIApplicantProfileInfo'),
        ),
        migrations.AlterField(
            model_name='priapplicantexamscoret3ptsctinfo',
            name='applicant_exam_score_t3ptsct',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='applicant_exam_score_t3ptsct_fk', to='pors_app.PRIApplicantProfileInfo'),
        ),
        migrations.AlterField(
            model_name='priapplicantexamscoret4arinfo',
            name='applicant_exam_score_t4ar',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='applicant_exam_score_t4ar_fk', to='pors_app.PRIApplicantProfileInfo'),
        ),
    ]
