# Generated by Django 2.2.3 on 2019-12-06 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pors_app', '0011_priapplicanttestarpinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='priapplicantexamscorearpinfo',
            name='ratings_arp',
            field=models.CharField(choices=[('Outstanding', 'Outstanding'), ('Average', 'Average'), ('Below Average', 'Below Average'), ('Poor', 'Poor'), ('On progress', 'On progress')], max_length=50),
        ),
        migrations.AlterField(
            model_name='priapplicantexamscorearpinfo',
            name='status_arp',
            field=models.CharField(choices=[('Passed', 'Passed'), ('Failed', 'Failed'), ('On progress', 'On progress')], max_length=50),
        ),
        migrations.AlterField(
            model_name='priapplicantexamscoreccainfo',
            name='ratings_cca',
            field=models.CharField(choices=[('Outstanding', 'Outstanding'), ('Average', 'Average'), ('Below Average', 'Below Average'), ('Poor', 'Poor'), ('On progress', 'On progress')], max_length=50),
        ),
        migrations.AlterField(
            model_name='priapplicantexamscoreccainfo',
            name='status_cca',
            field=models.CharField(choices=[('Passed', 'Passed'), ('Failed', 'Failed'), ('On progress', 'On progress')], max_length=50),
        ),
        migrations.AlterField(
            model_name='priapplicantexamscorescctinfo',
            name='ratings_scct',
            field=models.CharField(choices=[('Outstanding', 'Outstanding'), ('Average', 'Average'), ('Below Average', 'Below Average'), ('Poor', 'Poor'), ('On progress', 'On progress')], max_length=50),
        ),
        migrations.AlterField(
            model_name='priapplicantexamscorescctinfo',
            name='status_scct',
            field=models.CharField(choices=[('Passed', 'Passed'), ('Failed', 'Failed'), ('On progress', 'On progress')], max_length=50),
        ),
        migrations.AlterField(
            model_name='priapplicantexamscoret1peinfo',
            name='ratings_t1pe',
            field=models.CharField(choices=[('Outstanding', 'Outstanding'), ('Average', 'Average'), ('Below Average', 'Below Average'), ('Poor', 'Poor'), ('On progress', 'On progress')], max_length=50),
        ),
        migrations.AlterField(
            model_name='priapplicantexamscoret1peinfo',
            name='status_t1pe',
            field=models.CharField(choices=[('Passed', 'Passed'), ('Failed', 'Failed'), ('On progress', 'On progress')], max_length=50),
        ),
        migrations.AlterField(
            model_name='priapplicantexamscoret2seinfo',
            name='ratings_t2se',
            field=models.CharField(choices=[('Outstanding', 'Outstanding'), ('Average', 'Average'), ('Below Average', 'Below Average'), ('Poor', 'Poor'), ('On progress', 'On progress')], max_length=50),
        ),
        migrations.AlterField(
            model_name='priapplicantexamscoret2seinfo',
            name='status_t2se',
            field=models.CharField(choices=[('Passed', 'Passed'), ('Failed', 'Failed'), ('On progress', 'On progress')], max_length=50),
        ),
        migrations.AlterField(
            model_name='priapplicantexamscoret3einfo',
            name='ratings_t3e',
            field=models.CharField(choices=[('Outstanding', 'Outstanding'), ('Average', 'Average'), ('Below Average', 'Below Average'), ('Poor', 'Poor'), ('On progress', 'On progress')], max_length=50),
        ),
        migrations.AlterField(
            model_name='priapplicantexamscoret3einfo',
            name='status_t3e',
            field=models.CharField(choices=[('Passed', 'Passed'), ('Failed', 'Failed'), ('On progress', 'On progress')], max_length=50),
        ),
        migrations.AlterField(
            model_name='priapplicantexamscoret3ptsctinfo',
            name='ratings_t3ptsct',
            field=models.CharField(choices=[('Outstanding', 'Outstanding'), ('Average', 'Average'), ('Below Average', 'Below Average'), ('Poor', 'Poor'), ('On progress', 'On progress')], max_length=50),
        ),
        migrations.AlterField(
            model_name='priapplicantexamscoret3ptsctinfo',
            name='status_t3ptsct',
            field=models.CharField(choices=[('Passed', 'Passed'), ('Failed', 'Failed'), ('On progress', 'On progress')], max_length=50),
        ),
        migrations.AlterField(
            model_name='priapplicantexamscoret4arinfo',
            name='ratings_t4ar',
            field=models.CharField(choices=[('Outstanding', 'Outstanding'), ('Average', 'Average'), ('Below Average', 'Below Average'), ('Poor', 'Poor'), ('On progress', 'On progress')], max_length=50),
        ),
        migrations.AlterField(
            model_name='priapplicantexamscoret4arinfo',
            name='status_t4ar',
            field=models.CharField(choices=[('Passed', 'Passed'), ('Failed', 'Failed'), ('On progress', 'On progress')], max_length=50),
        ),
    ]
