# Generated by Django 2.2.3 on 2019-12-06 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pors_app', '0012_auto_20191206_2224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='priapplicantexamscorearpinfo',
            name='allow_retake_arp',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='priapplicantexamscoreccainfo',
            name='allow_retake_cca',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='priapplicantexamscorescctinfo',
            name='allow_retake_scct',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='priapplicantexamscoret1peinfo',
            name='allow_retake_t1pe',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='priapplicantexamscoret2seinfo',
            name='allow_retake_t2se',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='priapplicantexamscoret3einfo',
            name='allow_retake_t3e',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='priapplicantexamscoret3ptsctinfo',
            name='allow_retake_t3ptsct',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='priapplicantexamscoret4arinfo',
            name='allow_retake_t4ar',
            field=models.BooleanField(default=True),
        ),
    ]
